### ISSUE TITLE
Include tag doesn't work (but includeurl does)

### ISSUE THREAD

**Issue by renannprado** [Crashedmind/PlantUML-icons-GCP#1]
Hello, @Crashedmind 

First of all thanks a lot for this repo :smile: .
I was looking for something like this for some time already.

So, I was trying the examples shown here: https://crashedmind.github.io/PlantUMLHitchhikersGuide/gcp/gcp.html

But for some reason when I use the `include` tag in asciidoc, it doesn't work. Whereas when I use `includeurl` it does work.

I'm not sure if that's intended or not, but I just would like to know if you know what the reason could be or if there's a mistake in the documentation.

This is the error I get when I use `include` instead of `includeurl`.

Sample Diagram
```adoc
@startuml
!define GCPPuml https://raw.githubusercontent.com/Crashedmind/PlantUML-icons-GCP/master/dist
!include GCPPuml/GCPCommon.puml
!include GCPPuml/Compute/Cloud_Functions.puml
!include GCPPuml/Networking/Cloud_Firewall_Rules.puml
!include GCPPuml/Compute/Compute_Engine.puml
!include GCPPuml/Storage/Cloud_Storage.puml

Users(Users, "Friends", " ")
Mobile(Mobile, "", " ")
Client(Client, "Kid / Owner", " ")
Client(ClientMinecraft, "", " ")

Cloud_Functions(Cloud_FunctionsStart, "Start Server", "Cloud Functions")
Cloud_Functions(Cloud_FunctionsStop, "Stop Server", "Cloud Functions")
Cloud_Functions(Cloud_FunctionAdd, "Add a Friend", "Cloud Functions")

Compute_Engine(Compute_Engine, "MineCraft Server", "Compute Engine")

Cloud_Storage(Cloud_Storage, "MineCraft Backups", "Cloud Storage")

Cloud_Firewall_Rules(Cloud_Firewall_Rules_Starter,"Minecraft Backups", "Cloud Firewall Rules")
Cloud_Firewall_Rules(Cloud_Firewall_Rules_Friend,"Minecraft Backups", "Cloud Firewall Rules")
@enduml
```

Error message
```
Failed to generate image: PlantUML image generation failed: [From <input> (line 3) ]

@startuml
!define GCPPuml https://raw.githubusercontent.com/Crashedmind/PlantUML-icons-GCP/master/dist
!include architecture-diagram/GC ...
^^^^^
 cannot include architecture-diagram/https://raw.githubusercontent.com/Crashedmind/PlantUML-icons-GCP/master/dist/GCPCommon.puml

@startuml
!define GCPPuml https://raw.githubusercontent.com/Crashedmind/PlantUML-icons-GCP/master/dist
!include architecture-diagram/GCPPuml/GCPCommon.puml
!include architecture-diagram/GCPPuml/Compute/Cloud_Functions.puml
!include architecture-diagram/GCPPuml/Networking/Cloud_Firewall_Rules.puml
!include architecture-diagram/GCPPuml/Compute/Compute_Engine.puml
!include architecture-diagram/GCPPuml/Storage/Cloud_Storage.puml

Users(Users, "Friends", " ")
Mobile(Mobile, "", " ")
Client(Client, "Kid / Owner", " ")
Client(ClientMinecraft, "", " ")

Cloud_Functions(Cloud_FunctionsStart, "Start Server", "Cloud Functions")
Cloud_Functions(Cloud_FunctionsStop, "Stop Server", "Cloud Functions")
Cloud_Functions(Cloud_FunctionAdd, "Add a Friend", "Cloud Functions")

Compute_Engine(Compute_Engine, "MineCraft Server", "Compute Engine")

Cloud_Storage(Cloud_Storage, "MineCraft Backups", "Cloud Storage")

Cloud_Firewall_Rules(Cloud_Firewall_Rules_Starter,"Minecraft Backups", "Cloud Firewall Rules")
Cloud_Firewall_Rules(Cloud_Firewall_Rules_Friend,"Minecraft Backups", "Cloud Firewall Rules")
@enduml
```

And why one can use `!include <awslib/AWSCommon>` directly without using this repo's URL directly? is it possible to do the same here? I'm not sure if this `awslib` is included in the asciidoc compiler directly or what's going on there, but would be nice if it was as easy to use :smile:

**Comment by Crashedmind** [comment]
hi @renannprado,

'welcome!

The Plantuml include directive should support a URL per https://plantuml.com/preprocessing "!include now accepts a URL, so you don't need !includeurl" 
So you should check what version of PlantUML you/AsciiDoc are using - e.g. you can add %version to your diagram to see (ref https://plantuml.com/preprocessing) - and move to latest if possible.


Currently, the GCP icons are not part of https://plantuml.com/stdlib. There's an effort to standardise stdlib first - before adding more icon sets.

The AWSlib icons are part of  https://plantuml.com/stdlib - so can use "!include <awslib/AWSCommon>".

Note that all of this is implemented via the PlantUML extension for AsciiDoc - not AsciiDoc directly: https://asciidoctor.org/docs/asciidoctor-diagram/#plantuml. In other words, the problem/solution will be with Plantuml version used by AsciiDoc. 

Hope that helps,
Chris

**Comment by renannprado** [comment]
I'm doing some cleanup in my open issues and I believe this can be closed.
